name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
  - cron: 0 20 * * 0-6
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: starred --username pratham-saraf --repository stars --sort --token ${TOKEN} 
